[package]
name = "fnv_yaml"
version = "0.10.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
smash-fnv = { path = "../smash-fnv", features = ["serde"] }
serde_yaml = { version = "0.9" }
